apps/identity_web/lib/identity_web/router.ex
defmodule IdentityWeb.Router do
  use IdentityWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {IdentityWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  ## OAuth Authentication routes
  scope "/", IdentityWeb do
    pipe_through [:browser]

    get "/users/auth", UserAuthController, :new
    get "/users/register", UserAuthController, :register_page
    post "/users/register", UserAuthController, :register
    get "/users/login", UserAuthController, :login_page
    post "/users/login", UserAuthController, :login
    get "/users/login/cancel", UserAuthController, :cancel_login
    get "/users/email/check", UserAuthController, :check_email_page
    post "/users/email/check", UserAuthController, :check_email_token
    post "/users/email/check/new", UserAuthController, :resend_check_email_token
    get "/users/cgs/validation", UserAuthController, :validate_cgs_page
    post "/users/cgs/validation", UserAuthController, :validate_cgs
    get "/users/password/lost", UserAuthController, :lost_password_enter_email
    post("/users/password/lost", UserAuthController, :send_lost_password_code)
    put("/users/password/lost", UserAuthController, :change_lost_password)
    get "/users/consent", UserConsentController, :index
    post "/users/consent", UserConsentController, :consent

    get "/users/logout", UserAuthController, :logout
    post "/users/logout", UserAuthController, :logout_confirm
  end
end

apps/identity_web/lib/identity_web/controllers/user_consent_controller.ex
defmodule IdentityWeb.UserConsentController do
  use IdentityWeb, :controller

  alias Lenra.Errors.BusinessError
  require Logger

  #################
  ## Controllers ##
  #################

  def index(conn, %{"consent_challenge" => consent_challenge}) do
    # Get the consent request informations
    {:ok, response} = HydraApi.get_consent_request(consent_challenge)

    # if "skip" == true, the consent have already been granted.
    # We can directly accept the consent and redirect.
    if response.body["skip"] do
      # Consent
      {:ok, accept_response} =
        HydraApi.accept_consent(
          consent_challenge,
          response.body["requested_scope"],
          response.body["requested_access_token_audience"],
          # Session data
          %{
            access_token: %{},
            id_token: %{}
          }
        )

      # Redirect to hydra.
      redirect(conn, external: accept_response.body["redirect_to"])
    else
      # If we do not skip, get the user and show the consent page.
      case Lenra.Accounts.get_user(response.body["subject"]) do
        nil ->
          BusinessError.invalid_token_tuple()

        user ->
          # The "consent_challenge" is sent back using a hiddend field.
          # Here, the "client" is an object with additionnal informations.
          # The "requested_scope" are just a list of string.
          # We could create objects in the DB or just statically explain what the scope do.
          render(conn, "consent.html",
            user: user,
            scopes: response.body["requested_scope"],
            client: response.body["client"],
            action: :consent,
            consent_challenge: consent_challenge
          )
      end
    end
  end

  def consent(conn, %{"accept" => "false", "consent_challenge" => consent_challenge}) do
    # Here, the user denied the consent by clicking on "reject" button.
    # We tell hydra that the user rejected the consent.
    {:ok, response} = HydraApi.reject_consent(consent_challenge)

    # Then redirect to hydra.
    redirect(conn, external: response.body["redirect_to"])
  end

  def consent(conn, %{
        "accept" => "true",
        "consent_challenge" => consent_challenge,
        "remember_me" => remember
      }) do
    # Here, the user accepted the consent by clicking on "accept" button.

    {:ok, response} = HydraApi.get_consent_request(consent_challenge)

    {:ok, accept_response} =
      HydraApi.accept_consent(
        consent_challenge,
        response.body["requested_scope"],
        response.body["requested_access_token_audience"],
        # We can add data to the token if needed.
        %{
          # This data will be available when introspecting the token. Try to avoid sensitive information here,
          # unless you limit who can introspect tokens.
          access_token: %{},

          # This data will be available in the ID token.
          # The ID Token is the OpenId token that contain user informations.
          # See https://www.ory.sh/docs/oauth2-oidc/overview/oidc-concepts#the-id-token
          id_token: %{}
        },
        remember == "true"
      )

    redirect(conn, external: accept_response.body["redirect_to"])
  end
end

apps/identity_web/lib/identity_web/views/user_consent_view.ex
defmodule IdentityWeb.UserConsentView do
  use IdentityWeb, :view
end

apps/identity_web/lib/identity_web/templates/user_consent/consent.html.heex
<main class="arrows">
  <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/form.css")} media="print" onload='this.media="all"'/>
  <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/css/consent.css")} media="print" onload='this.media="all"'/>
  <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/form.js")}></script>
  <%= oauth_header "consent", @client %>
  <.form let={f} for={@conn} action={Routes.user_consent_path(@conn, @action)} >
    <p><%= raw(gettext("Hi <strong>%{email}</strong> !", email: @user.email)) %></p>
    <p><%= raw(gettext("<strong>%{app_name}</strong> is requesting access to your Lenra account.", app_name: get_client_name(@client))) %></p>
    <p><%= raw(gettext("If you accept, <strong>%{app_name}</strong> will have access to :", app_name: get_client_name(@client))) %></p>
    <ul>
      <%= for scope <- @scopes do %>
        <li><%= get_translated_scope_description(scope) %></li>
      <% end %>
    </ul>
    <%= if assigns[:consent_challenge] do %>
      <%= hidden_input f, :consent_challenge, value: @consent_challenge %>
    <% end %>

    <fieldset>
      <%= checkbox f, :remember_me %>
      <%= label f, :remember_me, gettext("Remember my choice") %>
    </fieldset>
    <nav>
      <%= submit gettext("Decline"), name: :accept, value: "false" %>
      <%= submit gettext("Accept"), name: :accept, value: "true", class: "primary" %>
    </nav>
    <%# = link gettext("Connect with another account"), to: Routes.user_auth_path(@conn, :lost_password_enter_email), class: "login btn link lenra-icon-chevron-right" %>
  </.form>
</main>

apps/identity_web/lib/identity_web/templates/user_consent/error.html.heex
<h2>Oops, something is wrong...</h2>
<p><%= @message %></p>